--SELECT * FROM INFORMATION_SCHEMA. TABLES  
--WHERE table_type='BASE TABLE' and table_schema='user_management'
CREATE SCHEMA IF NOT EXISTS user_management;

CREATE TABLE IF NOT EXISTS user_management.users(
     USER_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
     USERNAME VARCHAR(255) NOT NULL UNIQUE,
     FIRSTNAME VARCHAR(255) NOT NULL,
     LASTNAME VARCHAR(255) NOT NULL,
     GENDER VARCHAR(25) NOT NULL,
     EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_management.user_address(
     USER_ADDRESS_ID SERIAL PRIMARY KEY,
     USER_ID UUID NOT NULL,
     LOCATION VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_management.user_secrets(
     USER_SECRET_ID SERIAL PRIMARY KEY,
     USER_ID UUID NOT NULL,
     PASSKEY VARCHAR(255) NOT NULL
);